# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-AR-Db
version:      2.13
version_from: lib/Lingua/AR/Db.pm
installdirs:  site
requires:
    Lingua::AR::Word:              1.5.4
    MLDBM:                         0
    DB_File:			0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
