# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-AR-Db
version:      2.15
version_from: lib/Lingua/AR/Db.pm
installdirs:  site
requires:
    DB_File:                       0
    Lingua::AR::Word:              
    MLDBM:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
